### ISSUE TITLE
Linux Sphinx binary depends on GLIBC_2.14

### ISSUE THREAD

**Issue by donatelloOo** [trustin/sphinx-maven-plugin#11]
`/lib64/libc.so.6: version 'GLIBC_2.14' not found` while running on RedHat 6.4 with glibc-2.12: 

``` console
[INFO] Running Sphinx; output will be placed in /data1/jenkins/workspace/documentation/target/rtd
/var/lib/jenkins/.m2/repository/kr/motd/maven/sphinx-binary/https___github.com_trustin_sphinx-binary_releases_download_v0.3.0_sphinx.linux-x86_64/sphinx.linux-x86_64: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/_MEINq3ZQn/libz.so.1)
[INFO] Sphinx exited with code 1. Took 1081ms.
```
Is that a real prerequisite or just because this library has been built using glibc-2.14 ?

**Comment by trustin** [comment]
Yes. You need a newer version of Linux that ships glibc 2.14+. Alternatively, you can try installing glibc 2.14 in parallel, as described here: https://unix.stackexchange.com/q/176489 I think it's probably a better idea to upgrade to RHEL/CentOS 7.x, though.

**Comment by trustin** [comment]
FYI, the Linux binary is currently being built by Travis CI's 'trusty' image, which is Ubuntu 14.04. As far as I know, 14.04 is the oldest version where the Deadsnakes team provides the backported Python 3.6 packages - https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa.

I guess building the Linux binary in an older OS would take some extra effort without much gain. Also, there's a risk of retiring 'precise' images or reducing their availability, given that Travis CI folks have switched its default image from 'precise' (12.04) to 'trusty' quite some time ago.

**Comment by trustin** [comment]
> Is that a real prerequisite or just because this library has been built using glibc-2.14 ?

And.. if you don't mind building the sphinx binary by yourself, you can try to build it on RHEL 6.4, and the resulting binary will work just fine. However, it may take some effort.

**Comment by trustin** [comment]
For more information about building the stand-alone binary, visit https://github.com/trustin/sphinx-binary
I can build the stand-alone binary basically by running `./install.sh && ./build.sh`, but I never tried it on an old OS like that. It expects Python 3.6 is installed basically.

**Comment by donatelloOo** [comment]
Very complete answer.
I'm closing issue as there is not much to add.
Thank you!

**Comment by trustin** [comment]
Thanks for your understanding, @donatelloOo!
