### ISSUE TITLE
Support for local installation of Sphinx

### ISSUE THREAD

**Issue by digulla** [trustin/sphinx-maven-plugin#15]
The plugin comes with a precompiled Sphinx für Windows.

Add a way to use a locally installed Sphinx instead or document how to do that.

**Comment by trustin** [comment]
You can specify `binaryUrl` property, as documented in: https://trustin.github.io/sphinx-maven-plugin/configuration.html Please feel free to reopen if it doesn't work as expected.

**Comment by digulla** [comment]
This doesn't work when using Cygwin. Cygwin emulates Unix, so it knows how to run a script `sphinx-build` with she-bang `#!` at the top but the plugin doesn't support that.

What I would need is to pass extra arguments to the "binary". That way, I could make `bash.exe` the "binary" and pass `sphinx-build` (maybe with path) as the first argument. In your code, you have to use the List/Array based version of `ProcessBuilder` to execute the result, or this could fail for paths with spaces in them.

Spaces in paths is the reason why I can't simply write a wrapper `.bat` script (%* would pass all arguments to BASH but the quotes would be lost in the process).
