### ISSUE TITLE
add support for "-c" configuration directory cmd line option

### ISSUE THREAD

**Issue by jeacott1** [trustin/sphinx-maven-plugin#20]
Hi,
 any chance of adding support for the "-c" configuration directory cmd line option?
https://www.sphinx-doc.org/en/master/glossary.html#term-configuration-directory

it would make it much easier to process generated files without having to copy conf.py around.

thanks.

**Comment by trustin** [comment]
Thanks for reporting. I added `configDirectory` option in 2.10.0.
