### ISSUE TITLE
sphinxcontrib-youtube support

### ISSUE THREAD

**Issue by ccabanes** [trustin/sphinx-maven-plugin#8]
Include youtube video support into sphinx-plugin using, for example, shinxcontrib-youtube package

**Comment by trustin** [comment]
I'm curious if the plugin works with Sphinx 1.7.x. Would you mind trying it and letting me know?

**Comment by trustin** [comment]
sphinx-maven-plugin 2.2.2 now includes sphinxcontrib-youtube 0.2.0.
